### ISSUE TITLE
Warn about full From URLs

### ISSUE THREAD

**Issue by fklein-lu** [humanmade/hm-redirects#16]
When entering a full URL like `http://example.com/path` into the _From_ field, it will be saved into the database. But look ups only happen by path and query arguments, therefore the redirect will not get matched.

Let's account for this by warning users when they enter a full URL into the _From_ field.

**Comment by roborourke** [comment]
Feels like we could just run `normalise_url()` against it as part of data sanitisation. Not sure why you'd ever want to save the full URL?
