### ISSUE TITLE
Preserve URL parameters

### ISSUE THREAD

**Issue by glueckpress** [humanmade/hm-redirects#33]
Marketing/BD needs URL parameters to be preserved upon redirects.

Possibly duplicates #25, however, if just preserving parameters can be done without regexes, that would also work for our case.

**Comment by goldenapples** [comment]
Copying some of my comments over from a project repo where we addressed this issue.

> I could think of a couple different ways of going about it that might work:
>
> * Add an option where users can list all the query string parameters they'd want to have ignored in the match and passed directly through. This way you could specify things like `utm_` params be passed through without ignoring query string that are actually functional.
> * Allow specifying this at the individual redirect level. I think the Redirection plugin allows you to specify wildcards with an asterisk at the end of a pattern, and anything after that point is stripped from the match and passed directly through to the redirection URL. This one is good because it covers more than just query strings, you could move a whole section or rename a post type slug without having to enter individual redirects for each page in the section.

I don't think ignoring _all_ query parameters and passing them through to the redirect makes sense. However, a filter that could be used to whitelist ignored query parameters would be useful in a number of cases.

**Comment by glueckpress** [comment]
> I don't think ignoring all query parameters and passing them through to the redirect makes sense. 

@goldenapples Great point, thanks. 👍
Copying over your example from https://github.com/humanmade/platform-site/issues/313 for reference: when something like `?cat=oldnews` redirects to `/category/news` it definitely makes sense to strip the query parameter from the target URL.

> Add an option where users can list all the query string parameters they'd want to have ignored in the match and passed directly through.

Having an ‘allowed-list’ type of option sounds great. I’d like to suggest we also consider cases where a user can’t predict which exact query parameters will be appended to the URL but just need _all_ of them passed through. This would be covered by a solution like:

> Allow specifying this at the individual redirect level. I think the Redirection plugin allows you to specify wildcards with an asterisk at the end of a pattern, and anything after that point is stripped from the match and passed directly through to the redirection URL.

I love the  flexibility currently provided via _Safe Redirect Manager_ on humanmade.com ([admin page](https://humanmade.com/wp-admin/edit.php?post_type=redirect_rule)):
- Just entering a source path and target URL will give you a straight redirect.
- Appending a `*` wildcard character will match all requests with the base.
- Enabling the _Regular Expressions_ option will disable wildcards and let you work with actual an RegEx.

**Comment by roborourke** [comment]
So part of the reason we don't do these:

- Appending a * wildcard character will match all requests with the base.
- Enabling the Regular Expressions option will disable wildcards and let you work with actual an RegEx.

It's really hard to make those perform at scale without some custom tables and db queries. Performance is the crucial component of and why HM Redirects exist. Lots of redirects - use HM Redirects, a small number of complicated redirects - use Safe Redirect Manager

For context HM Redirects takes a hash of the URL and uses that for the lookup in the db.
