### ISSUE TITLE
URL normalisation bug

### ISSUE THREAD

**Issue by svandragt** [humanmade/hm-redirects#45]
The following url cannot be added to https://launch.hmn.md/:

`https://github.com/pulls?q=is%3Aopen+is%3Apr+archived%3Afalse+user%3Ahumanmade+label%3A%22reviewer+needed%22+sort%3Aupdated-desc+`

In particular the double quotes are stripped either on save or on redirection, which means this link breaks for labels containing multiple words. https://launch.hm/reviewer-needed

From a cursory glance it seems to the the source of the problem affecting https://github.com/humanmade/hmn.md/blob/001d498a26ec129ac998c49ae9aee8b7a92d93a5/content/themes/launch/inc/namespace.php#L87

**Comment by roborourke** [comment]
May be fixed by v0.6.0

**Comment by roborourke** [comment]
Closing out as fixed
