### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by kovshenin** [humanmade/hm-redirects#66]
There's at least one deprecated warning with hm-redirects on PHP 8.1:

```
PHP Deprecated:  str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated in /usr/src/app/vendor/humanmade/hm-redirects/includes/handle-redirects.php on line 33
```

Acceptance criteria:

- [x] Deprecation warning fixed
- [x] Fix any problems reported by `phpcs` with `--standard=PHPCompatibility --runtime-set testVersion 8.1`
- [x] Test plugin functionality in a PHP 8.1 environment
- [x] Release new version with PHP 8.1 support

**Comment by veselala** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/hm-redirects/66?planning-poker) with ZenHub @ferschubert-hm @kovshenin @mikelittle

**Comment by veselala** [comment]
@jerico @wisyhambolu we've estimated this one to 3SP and moved it to the backlog.

**Comment by robindevitt** [comment]
Merged and a new release has been created.
